# Generated by Django 3.1.1 on 2020-09-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark_name', models.TextField(null=True, verbose_name='Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipset_name', models.TextField(null=True, verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.IntegerField()),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison.benchmark')),
                ('chipset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparison.chipset')),
            ],
        ),
    ]
