# Generated by Django 3.1.1 on 2020-09-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtervalue',
            old_name='values',
            new_name='comparison_values',
        ),
    ]
