# Generated by Django 3.1.1 on 2020-09-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0002_auto_20200925_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterchoices',
            old_name='product',
            new_name='chipset',
        ),
        migrations.RemoveField(
            model_name='filterchoices',
            name='company',
        ),
        migrations.RemoveField(
            model_name='filterchoices',
            name='parameter',
        ),
        migrations.AddField(
            model_name='filterchoices',
            name='benchmark',
            field=models.TextField(null=True, verbose_name='Parameter'),
        ),
    ]
