# Generated by Django 3.1.1 on 2020-09-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0002_auto_20200930_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtervalue',
            old_name='comparison_values',
            new_name='values',
        ),
    ]
