# Generated by Django 3.1.1 on 2020-09-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0004_auto_20200930_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filtervalue',
            old_name='final_values',
            new_name='values',
        ),
    ]
